### ISSUE TITLE
Can't change any setting

### ISSUE THREAD

**Issue by popjunkie79** [h3llrais3r/Auto-Subliminal#11]
Since Version 2.2.0, when I try to change any setting like the Video Path in the Config tab in the browser window, I always get an error 500. When I restart the server, it defaults to the auto-subliminal folder again. I am therefore unable to get the program to work.

**Comment by h3llrais3r** [comment]
Please provide a (debug) log with the error.
I've just tried to reproduce it but everything is saved without any error.

**Comment by popjunkie79** [comment]
D:\Users\Nico Anton\Downloads\Auto-Subliminal-master>python AutoSubliminal.py
Traceback (most recent call last):
  File "AutoSubliminal.py", line 134, in <module>
    sys.exit(main())
  File "AutoSubliminal.py", line 37, in main
    import autosubliminal
  File "D:\Users\Nico Anton\Downloads\Auto-Subliminal-master\autosubliminal\__init__.py", line 68, in <module>
    LOGFILE = AutoSubliminal.log
NameError: name 'AutoSubliminal' is not defined

**Comment by popjunkie79** [comment]
I set the same settings as you and when I try to start it using the command I get this

**Comment by h3llrais3r** [comment]
Ok, I tried with a completely new setup and I have indeed a http 500 error.
Will fix it asap.

**Comment by h3llrais3r** [comment]
@popjunkie79 Can you try again and provide your feedback?

**Comment by popjunkie79** [comment]
Yep, it seems to be fixed! Thank you very much!

**Comment by h3llrais3r** [comment]
Thanks for your feedback. You're welcome. 😉

**Comment by Baskent93** [comment]
Hello there,
I am newbie so please execuse me if I am making mistake. I installed it, but unfortunately I can't save my config. My config.properties file is 0 byte, empty file btw. Here's my output in terminal: (ignore UI related stuff, I guess it is because of my low resolution)
` sudo python AutoSubliminal.py 
INFO: Initializing variables and loading config.
********************************************************************
ERROR: Not a valid configuration file! Using default values instead!
********************************************************************
ERROR: Required config section is missing. Using default values instead.
ERROR: Required variable PATH is missing. Using current working directory instead.
ERROR: Required variable VIDEOPATHS is missing. Using current working directory instead.
ERROR: Required variable LOGFILE is missing. Using 'AutoSuliminal.log' instead.
ERROR: The webserver section is required. Now setting the default values (0.0.0.0:8083).
WARNING: The webserver is started without authentication.
INFO: Succesfully created the sqlite database.
INFO: Starting output to log.
INFO: Bye.
[26/Jun/2017:00:24:27] ENGINE Bus STARTING
[26/Jun/2017:00:24:27] ENGINE Starting WebSocket processing
[26/Jun/2017:00:24:27] ENGINE Serving on http://0.0.0.0:8083
[26/Jun/2017:00:24:27] ENGINE Bus STARTED
[0626/002435:ERROR:nss_util.cc(94)] Failed to create /home/kucet/.pki/nssdb directory.
[0626/002435:FATAL:chrome_main_delegate.cc(413)] Check failed: process_type.empty(). Unable to get the user data directory for process type: zygote
#0 0x7f852572779e base::debug::StackTrace::StackTrace()
#1 0x7f8525743227 logging::LogMessage::~LogMessage()
#2 0x56342ec675c3 <unknown>
#3 0x7f8520a2873a <unknown>
#4 0x7f8520a26fcd content::ContentMain()
#5 0x56342ec6690c <unknown>
#6 0x7f8510bcd3f1 __libc_start_main
#7 0x56342ec667da <unknown>

[3451:3451:0626/002436:FATAL:zygote_host_impl_linux.cc(182)] Check failed: ReceiveFixedMessage(fds[0], kZygoteBootMessage, sizeof(kZygoteBootMessage), &boot_pid). 
#0 0x7f6d1821c79e base::debug::StackTrace::StackTrace()
#1 0x7f6d18238227 logging::LogMessage::~LogMessage()
#2 0x7f6d1322ab63 content::ZygoteHostImpl::LaunchZygote()
#3 0x7f6d13229bd2 content::ZygoteCommunication::Init()
#4 0x7f6d1322a14e content::CreateZygote()
#5 0x7f6d12ee4d57 content::BrowserMainLoop::EarlyInitialization()
#6 0x7f6d12ee7eaf <unknown>
#7 0x7f6d12ee10f2 content::BrowserMain()
#8 0x7f6d1351cce4 <unknown>
#9 0x7f6d1351bff1 content::ContentMain()
#10 0x55ac349bf90c <unknown>
#11 0x7f6d036c23f1 __libc_start_main
#12 0x55ac349bf7da <unknown>

Aborted (core dumped)

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:66:13: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:97:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:98:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:104:39: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:107:39: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:158:33: The :focused pseudo-class is deprecated. Use :focus instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:174:38: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:175:40: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:176:53: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:177:55: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:178:53: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:179:55: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:180:48: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:181:50: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:182:44: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:183:46: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:184:52: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:185:54: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:186:52: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:187:54: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:188:47: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:189:49: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:190:21: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:191:23: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:196:34: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:286:15: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(firefox:3465): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:309:15: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(firefox:3465): Gtk-WARNING **: Theme directory  imported-Humanity/192 of theme Lubuntu has no size field

127.0.0.1 - - [26/Jun/2017:00:26:02] "GET /home/ HTTP/1.1" 200 14183 "http://localhost:8083/system/shutdown" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/55.0.2883.87 Chrome/55.0.2883.87 Safari/537.36"
127.0.0.1 - - [26/Jun/2017:00:26:05] "GET /system/message HTTP/1.1" 101 - "" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/55.0.2883.87 Chrome/55.0.2883.87 Safari/537.36"
127.0.0.1 - - [26/Jun/2017:00:26:16] "GET /config/general/ HTTP/1.1" 200 41943 "http://localhost:8083/home/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/55.0.2883.87 Chrome/55.0.2883.87 Safari/537.36"
127.0.0.1 - - [26/Jun/2017:00:26:17] "GET /system/message HTTP/1.1" 101 - "" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/55.0.2883.87 Chrome/55.0.2883.87 Safari/537.36"
[26/Jun/2017:00:26:30] HTTP 
Request Headers:
  CONNECTiON: keep-alive
  REFERER: http://localhost:8083/config/general/
  ORiGiN: http://localhost:8083
  Remote-Addr: 127.0.0.1
  Content-Length: 375
  USER-AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/55.0.2883.87 Chrome/55.0.2883.87 Safari/537.36
  HOST: localhost:8083
  UPGRADE-INSECURE-REQUESTS: 1
  CACHE-CONTROL: max-age=0
  ACCEPT-ENCODiNG: gzip, deflate, br
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  COOKiE: _pk_id.1.1fff=29cd23a4e1565e50.1498335985.1.1498337352.1498335985.
  ACCEPT-LANGUAGE: tr-TR,tr;q=0.8,en-US;q=0.6,en;q=0.4
  Content-Type: application/x-www-form-urlencoded
[26/Jun/2017:00:26:30] HTTP 
Traceback (most recent call last):
  File "/home/kucet/AS/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/home/kucet/AS/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/kucet/AS/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/kucet/AS/autosubliminal/webserver.py", line 257, in save
    return Config.save_and_restart_if_needed()
  File "/home/kucet/AS/autosubliminal/webserver.py", line 201, in save_and_restart_if_needed
    restart = config.write_config()
  File "/home/kucet/AS/autosubliminal/config.py", line 1433, in write_config
    save_config_section()
  File "/home/kucet/AS/autosubliminal/config.py", line 974, in save_config_section
    cfg.set(section, "videopaths", str(videopaths))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0130' in position 12: ordinal not in range(128)
2017-06-26 00:26:30,497 ERROR [26/Jun/2017:00:26:30] HTTP 
Traceback (most recent call last):
  File "/home/kucet/AS/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/home/kucet/AS/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/kucet/AS/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/kucet/AS/autosubliminal/webserver.py", line 257, in save
    return Config.save_and_restart_if_needed()
  File "/home/kucet/AS/autosubliminal/webserver.py", line 201, in save_and_restart_if_needed
    restart = config.write_config()
  File "/home/kucet/AS/autosubliminal/config.py", line 1433, in write_config
    save_config_section()
  File "/home/kucet/AS/autosubliminal/config.py", line 974, in save_config_section
    cfg.set(section, "videopaths", str(videopaths))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0130' in position 12: ordinal not in range(128)
127.0.0.1 - - [26/Jun/2017:00:26:30] "POST /config/general/save HTTP/1.1" 500 513 "http://localhost:8083/config/general/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/55.0.2883.87 Chrome/55.0.2883.87 Safari/537.36"
127.0.0.1 - - [26/Jun/2017:00:26:39] "GET /system/message HTTP/1.1" 101 - "" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/55.0.2883.87 Chrome/55.0.2883.87 Safari/537.36"
127.0.0.1 - - [26/Jun/2017:00:26:43] "GET /log/viewLog HTTP/1.1" 200 9101 "http://localhost:8083/config/general/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/55.0.2883.87 Chrome/55.0.2883.87 Safari/537.36"
127.0.0.1 - - [26/Jun/2017:00:26:44] "GET /system/message HTTP/1.1" 101 - "" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/55.0.2883.87 Chrome/55.0.2883.87 Safari/537.36"
127.0.0.1 - - [26/Jun/2017:00:26:53] "GET /home/ HTTP/1.1" 200 14183 "http://localhost:8083/log/viewLog" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/55.0.2883.87 Chrome/55.0.2883.87 Safari/537.36"
127.0.0.1 - - [26/Jun/2017:00:26:54] "GET /system/message HTTP/1.1" 101 - "" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/55.0.2883.87 Chrome/55.0.2883.87 Safari/537.36" `
