### ISSUE TITLE
web browser config on headless Raspberry Pi?

### ISSUE THREAD

**Issue by bokiroki** [h3llrais3r/Auto-Subliminal#19]
Hi, I'm wanna use your script with sonarr/radarr.. Can i ask few questions:
so i must:
   1. install python 
   2. download your repository *** where is the best place to put that folder on raspberry pi? ***
   3. navigate to that folder in terminal and enter "python setup.py install"
   4. also from that folder in terminal enter "python AutoSubliminal.py"
   5. A web browser should now open - what if i dont have web browser on raspberry pi and want to enter that web adress from my pc in the same local network?

Also, can you tell me can i call for your script with sonarr/radarr with "Custom Post Processor Script" that is executed after tv show/movie is downloaded/moved

Thanks and sorry for noob questions

**Comment by h3llrais3r** [comment]
First of all, you cannot use this as a post processor script, because this is not a script.
This is a standalone application, like sonarr, sickrage, ...
You can used it next to it.
Let me explain: you can let sonarr (or any other tool) download your files to a specific folder, that is not automatically processed again by the tool. You can configure Auto-Subliminal to scan that folder for videos with missing subtitles. You can define a post processing script in Auto-Subliminal to copy the video together with it's found subtitle back to a folder where your download tool is listening for files to be processed. 
Or way is to let autosubliminal scan your entire video collection for missing subtitles, but this may give problems for finding matching subtitles if you renamed your video files...
So my advise is the first suggestion. This is how I'm using it for years now in combination with SickRage.

About your other questions:
2. I think you can put it where you want
5. Then you open it from your other pc in your network. You just need the ip of the machine where it's running on, port 8083
-> now you should be able to configure it from your other pc through the web ui

Please let me know if this explains how you can set it up.

**Comment by bokiroki** [comment]
Do i install default or development branch? i see that you remove step 2. navigate to that folder in terminal and enter "python setup.py install" from development branch..

So to understand better first suggestion (english is not my native language)
transmission first download movie to download folder
than Radarr pick up that movie, make a folder with that movie name in my movie collection folder and put that movie in that folder (without renaming movie file)
than how to trigger auto subliminal automaticaly after that, do i must wait auto subliminal shedule to scan that folder? is there some command line that trigger auto subliminal and can i put that command in
Custom Post Processor Script..

"You can define a post processing script in Auto-Subliminal to copy the video together with it's found subtitle back to a folder where your download tool is listening for files to be processed."
    - is that script present in web gui menu or i must make one myself?

**Comment by h3llrais3r** [comment]
Well, I'm just busy with trying to get rid of installation 😉 
If you want a stable version, go for master branch and do the installation. If you want the latest version, use the development branch, where you don't need to install anything. (I will probably release to master in the near future)

To tool scans the configured folder(s) on a specfic interval, which can also be configured in the tool also.
You can also run a scan manually for the system menu (but that's only possible from the development branch)
Like I already said, this is no library or script, so you need to use the tool to do everything.
Please go through all the config pages to set it up. For almost all config properties there is an info button available to explain what it does.

About the post processing script: that's something you need to create yourself. It's just a copy/move of a file from the current location to your desired location.
