### ISSUE TITLE
[Request] Make additional language as an option when Default language is missing

### ISSUE THREAD

**Issue by halali** [h3llrais3r/Auto-Subliminal#39]
Hi

i want to ask if will be possible to make additional language serchable ony if default language is missing...
for example i have file default language is CS and additional is SK... these language are simmilar...
so i want that primary download language CS and search for SK only if there is no CS language..
when CS language is present dont search for additional language anymore.
but if is there only additional language SK try to search for default language...

i hope you understand it

**Comment by h3llrais3r** [comment]
I understand what you mean, but I don't really like that...
Next to that, when will you decide when no primary language is found? Because it can take some time until certain languages are available. You have the risk that you download an additional language before your primary language, which is not the intended behaviour.

I suggest that you define both. This should result in having 2 flags in the screen and it will stay in the list until both languages are found. If you decide after some time that you have enough with 1 language (can be primary or additional) you can skip the episode manually.

**Comment by halali** [comment]
Yes the problem is, usualy when sk is released no1 make cz and if someone make cz no1 make sk...
Problem is when i chose both langs i have 3100 items that need subs

**Comment by h3llrais3r** [comment]
I have 1 other alternative, but this only works when you have a temporary location (like I'm doing) where your videos are stored until all your subtitles are found. With a postprocessing script you can move your video files to their final destination.

![image](https://user-images.githubusercontent.com/1945295/40443969-3c92ae6c-5ec8-11e8-9e74-b59c80b039a2.png)

So basically:
- have a temporary location where you store your videos before they are moved to their final location
- create a post processing script that moves the video file and the subtitle to the final location
- enable individual postprocessing

if you do it like this, even when you define multiple subtitles, the files will be moved once the first subtitle is found. This means that the next time the diskscanner is running, the video will be removed from the wanted list because it will no longer be found. But like I said before, this only works if you store the files in a temporary location and auto-subliminal is watching this temporary location.

I hope you understand what I mean.

**Comment by halali** [comment]
Yes i understand and thank you,but i think this is not good solution for me becouse sonarr organize mine files...

Will try to work with that i have...

Thanks.

**Comment by halali** [comment]
im noob at coding, but i make changes that i needet to do that thing... will try to make some setting for it and will make PR after...
